language: cpp

compiler:
  - clang
  - gcc

env:
  matrix:
    - SHARED=OFF
    - SHARED=ON

before_script:
  - mkdir build
  - cd build
  - cmake .. -DUSE_SHARED_CURL=$SHARED -DUSE_SHARED_GIFLIB=$SHARED -DUSE_SHARED_JPEGLIB=$SHARED -DUSE_SHARED_ZLIB=$SHARED -DUSE_SHARED_LIBPNG=$SHARED -DUSE_SHARED_LIBLOADPNG=$SHARED -DUSE_SHARED_TINYXML=$SHARED -DUSE_SHARED_GTEST=$SHARED -DUSE_SHARED_PIXMAN=$SHARED -DUSE_SHARED_ALLEGRO4=$SHARED

script:
  - "make"
  - "make run_non_ui_tests"
