language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - ENABLE_UI=ON
    - os: linux
      addons:
        apt:
          packages:
            - libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - ENABLE_UI=OFF
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          packages:
            - libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - ENABLE_UI=ON
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - ENABLE_UI=ON
        - XVFB=xvfb-run

before_script:
  - mkdir build
  - cd build
  - $XVFB cmake .. -DENABLE_TESTS=ON -DENABLE_UI=$ENABLE_UI

script:
  - make
  - |
    if ctest --output-on-failure ; then
      if [[ "$ENABLE_UI" == "OFF" ]]; then
        export ASEPRITE=$PWD/bin/aseprite
        git clone https://github.com/aseprite/tests.git
        cd tests
        $XVFB bash run-tests.sh
      fi
    fi
